// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/peer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId   []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	AddTs    int64  `protobuf:"varint,4,opt,name=add_ts,json=addTs,proto3" json:"add_ts,omitempty"`
	AccessTs int64  `protobuf:"varint,5,opt,name=access_ts,json=accessTs,proto3" json:"access_ts,omitempty"`
}

func (x *ContactMsg) Reset() {
	*x = ContactMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactMsg) ProtoMessage() {}

func (x *ContactMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactMsg.ProtoReflect.Descriptor instead.
func (*ContactMsg) Descriptor() ([]byte, []int) {
	return file_pb_peer_proto_rawDescGZIP(), []int{0}
}

func (x *ContactMsg) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ContactMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactMsg) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactMsg) GetAddTs() int64 {
	if x != nil {
		return x.AddTs
	}
	return 0
}

func (x *ContactMsg) GetAccessTs() int64 {
	if x != nil {
		return x.AccessTs
	}
	return 0
}

var File_pb_peer_proto protoreflect.FileDescriptor

var file_pb_peer_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x54, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_peer_proto_rawDescOnce sync.Once
	file_pb_peer_proto_rawDescData = file_pb_peer_proto_rawDesc
)

func file_pb_peer_proto_rawDescGZIP() []byte {
	file_pb_peer_proto_rawDescOnce.Do(func() {
		file_pb_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_peer_proto_rawDescData)
	})
	return file_pb_peer_proto_rawDescData
}

var file_pb_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_peer_proto_goTypes = []interface{}{
	(*ContactMsg)(nil), // 0: contact.pb.ContactMsg
}
var file_pb_peer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_peer_proto_init() }
func file_pb_peer_proto_init() {
	if File_pb_peer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_peer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_peer_proto_goTypes,
		DependencyIndexes: file_pb_peer_proto_depIdxs,
		MessageInfos:      file_pb_peer_proto_msgTypes,
	}.Build()
	File_pb_peer_proto = out.File
	file_pb_peer_proto_rawDesc = nil
	file_pb_peer_proto_goTypes = nil
	file_pb_peer_proto_depIdxs = nil
}
