// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/group_admin.proto

package grouppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志类型
type GroupLog_LogType int32

const (
	GroupLog_CREATE          GroupLog_LogType = 0 // 创建群
	GroupLog_NAME            GroupLog_LogType = 1 // 设置群名
	GroupLog_AVATAR          GroupLog_LogType = 2 // 设置群头像
	GroupLog_NOTICE          GroupLog_LogType = 3 // 设置群公告
	GroupLog_AUTO_JOIN_GROUP GroupLog_LogType = 4 // 设置入群免审核
	GroupLog_DEPOSIT_PEER_ID GroupLog_LogType = 5 // 离线消息寄存节点
	GroupLog_MEMBER          GroupLog_LogType = 6 // 群成员操作
	GroupLog_DISBAND         GroupLog_LogType = 7 // 解散群
)

// Enum value maps for GroupLog_LogType.
var (
	GroupLog_LogType_name = map[int32]string{
		0: "CREATE",
		1: "NAME",
		2: "AVATAR",
		3: "NOTICE",
		4: "AUTO_JOIN_GROUP",
		5: "DEPOSIT_PEER_ID",
		6: "MEMBER",
		7: "DISBAND",
	}
	GroupLog_LogType_value = map[string]int32{
		"CREATE":          0,
		"NAME":            1,
		"AVATAR":          2,
		"NOTICE":          3,
		"AUTO_JOIN_GROUP": 4,
		"DEPOSIT_PEER_ID": 5,
		"MEMBER":          6,
		"DISBAND":         7,
	}
)

func (x GroupLog_LogType) Enum() *GroupLog_LogType {
	p := new(GroupLog_LogType)
	*p = x
	return p
}

func (x GroupLog_LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupLog_LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_group_admin_proto_enumTypes[0].Descriptor()
}

func (GroupLog_LogType) Type() protoreflect.EnumType {
	return &file_proto_group_admin_proto_enumTypes[0]
}

func (x GroupLog_LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupLog_LogType.Descriptor instead.
func (GroupLog_LogType) EnumDescriptor() ([]byte, []int) {
	return file_proto_group_admin_proto_rawDescGZIP(), []int{0, 0}
}

// 群成员具体操作
type GroupLog_MemberOperate int32

const (
	GroupLog_NONE     GroupLog_MemberOperate = 0 // 无操作
	GroupLog_CREATOR  GroupLog_MemberOperate = 1 // 创建者
	GroupLog_APPLY    GroupLog_MemberOperate = 2 // 申请
	GroupLog_AGREE    GroupLog_MemberOperate = 3 // 同意
	GroupLog_REJECTED GroupLog_MemberOperate = 4 // 拒绝
	GroupLog_REMOVE   GroupLog_MemberOperate = 5 // 移除
	GroupLog_EXIT     GroupLog_MemberOperate = 6 // 退出
)

// Enum value maps for GroupLog_MemberOperate.
var (
	GroupLog_MemberOperate_name = map[int32]string{
		0: "NONE",
		1: "CREATOR",
		2: "APPLY",
		3: "AGREE",
		4: "REJECTED",
		5: "REMOVE",
		6: "EXIT",
	}
	GroupLog_MemberOperate_value = map[string]int32{
		"NONE":     0,
		"CREATOR":  1,
		"APPLY":    2,
		"AGREE":    3,
		"REJECTED": 4,
		"REMOVE":   5,
		"EXIT":     6,
	}
)

func (x GroupLog_MemberOperate) Enum() *GroupLog_MemberOperate {
	p := new(GroupLog_MemberOperate)
	*p = x
	return p
}

func (x GroupLog_MemberOperate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupLog_MemberOperate) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_group_admin_proto_enumTypes[1].Descriptor()
}

func (GroupLog_MemberOperate) Type() protoreflect.EnumType {
	return &file_proto_group_admin_proto_enumTypes[1]
}

func (x GroupLog_MemberOperate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupLog_MemberOperate.Descriptor instead.
func (GroupLog_MemberOperate) EnumDescriptor() ([]byte, []int) {
	return file_proto_group_admin_proto_rawDescGZIP(), []int{0, 1}
}

type GroupLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // 日志ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`                                                   // 群组ID
	PeerId        []byte                 `protobuf:"bytes,3,opt,name=peerId,proto3" json:"peerId,omitempty"`                                                     // 操作人
	LogType       GroupLog_LogType       `protobuf:"varint,4,opt,name=logType,proto3,enum=admin.pb.GroupLog_LogType" json:"logType,omitempty"`                   // 日志类型
	Member        *GroupLog_Member       `protobuf:"bytes,5,opt,name=member,proto3" json:"member,omitempty"`                                                     // 成员ID
	MemberOperate GroupLog_MemberOperate `protobuf:"varint,6,opt,name=memberOperate,proto3,enum=admin.pb.GroupLog_MemberOperate" json:"memberOperate,omitempty"` // 成员操作
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                                                   // 附带内容
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`                                            // 时间戳
	Lamportime    uint64                 `protobuf:"varint,9,opt,name=lamportime,proto3" json:"lamportime,omitempty"`                                            // lamport时间戳
	Signature     []byte                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`                                              // 签名
}

func (x *GroupLog) Reset() {
	*x = GroupLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLog) ProtoMessage() {}

func (x *GroupLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLog.ProtoReflect.Descriptor instead.
func (*GroupLog) Descriptor() ([]byte, []int) {
	return file_proto_group_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GroupLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupLog) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupLog) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *GroupLog) GetLogType() GroupLog_LogType {
	if x != nil {
		return x.LogType
	}
	return GroupLog_CREATE
}

func (x *GroupLog) GetMember() *GroupLog_Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GroupLog) GetMemberOperate() GroupLog_MemberOperate {
	if x != nil {
		return x.MemberOperate
	}
	return GroupLog_NONE
}

func (x *GroupLog) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GroupLog) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GroupLog) GetLamportime() uint64 {
	if x != nil {
		return x.Lamportime
	}
	return 0
}

func (x *GroupLog) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GroupLog_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *GroupLog_Member) Reset() {
	*x = GroupLog_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLog_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLog_Member) ProtoMessage() {}

func (x *GroupLog_Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLog_Member.ProtoReflect.Descriptor instead.
func (*GroupLog_Member) Descriptor() ([]byte, []int) {
	return file_proto_group_admin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GroupLog_Member) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GroupLog_Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupLog_Member) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_proto_group_admin_proto protoreflect.FileDescriptor

var file_proto_group_admin_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x62, 0x22, 0x99, 0x05, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x2e, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0d, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x44, 0x0a, 0x06, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x22, 0x7a, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41, 0x4d, 0x45,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x55,
	0x54, 0x4f, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x04, 0x12,
	0x13, 0x0a, 0x0f, 0x44, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f,
	0x49, 0x44, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x06,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x53, 0x42, 0x41, 0x4e, 0x44, 0x10, 0x07, 0x22, 0x60, 0x0a,
	0x0d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x50, 0x50, 0x4c, 0x59, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x47, 0x52, 0x45, 0x45, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x58, 0x49, 0x54, 0x10, 0x06, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_group_admin_proto_rawDescOnce sync.Once
	file_proto_group_admin_proto_rawDescData = file_proto_group_admin_proto_rawDesc
)

func file_proto_group_admin_proto_rawDescGZIP() []byte {
	file_proto_group_admin_proto_rawDescOnce.Do(func() {
		file_proto_group_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_group_admin_proto_rawDescData)
	})
	return file_proto_group_admin_proto_rawDescData
}

var file_proto_group_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_group_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_group_admin_proto_goTypes = []interface{}{
	(GroupLog_LogType)(0),       // 0: admin.pb.GroupLog.LogType
	(GroupLog_MemberOperate)(0), // 1: admin.pb.GroupLog.MemberOperate
	(*GroupLog)(nil),            // 2: admin.pb.GroupLog
	(*GroupLog_Member)(nil),     // 3: admin.pb.GroupLog.Member
}
var file_proto_group_admin_proto_depIdxs = []int32{
	0, // 0: admin.pb.GroupLog.logType:type_name -> admin.pb.GroupLog.LogType
	3, // 1: admin.pb.GroupLog.member:type_name -> admin.pb.GroupLog.Member
	1, // 2: admin.pb.GroupLog.memberOperate:type_name -> admin.pb.GroupLog.MemberOperate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_group_admin_proto_init() }
func file_proto_group_admin_proto_init() {
	if File_proto_group_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_group_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupLog_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_group_admin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_group_admin_proto_goTypes,
		DependencyIndexes: file_proto_group_admin_proto_depIdxs,
		EnumInfos:         file_proto_group_admin_proto_enumTypes,
		MessageInfos:      file_proto_group_admin_proto_msgTypes,
	}.Build()
	File_proto_group_admin_proto = out.File
	file_proto_group_admin_proto_rawDesc = nil
	file_proto_group_admin_proto_goTypes = nil
	file_proto_group_admin_proto_depIdxs = nil
}
