// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/group_admin_pull.proto

package grouppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupLogHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	HeadId  string `protobuf:"bytes,2,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	TailId  string `protobuf:"bytes,3,opt,name=tail_id,json=tailId,proto3" json:"tail_id,omitempty"`
	Length  int32  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Hash    []byte `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *GroupLogHash) Reset() {
	*x = GroupLogHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_admin_pull_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLogHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLogHash) ProtoMessage() {}

func (x *GroupLogHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_admin_pull_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLogHash.ProtoReflect.Descriptor instead.
func (*GroupLogHash) Descriptor() ([]byte, []int) {
	return file_proto_group_admin_pull_proto_rawDescGZIP(), []int{0}
}

func (x *GroupLogHash) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupLogHash) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *GroupLogHash) GetTailId() string {
	if x != nil {
		return x.TailId
	}
	return ""
}

func (x *GroupLogHash) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GroupLogHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GroupLogIDPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftNum int32  `protobuf:"varint,1,opt,name=leftNum,proto3" json:"leftNum,omitempty"`
	LogId   string `protobuf:"bytes,2,opt,name=logId,proto3" json:"logId,omitempty"`
}

func (x *GroupLogIDPack) Reset() {
	*x = GroupLogIDPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_admin_pull_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLogIDPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLogIDPack) ProtoMessage() {}

func (x *GroupLogIDPack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_admin_pull_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLogIDPack.ProtoReflect.Descriptor instead.
func (*GroupLogIDPack) Descriptor() ([]byte, []int) {
	return file_proto_group_admin_pull_proto_rawDescGZIP(), []int{1}
}

func (x *GroupLogIDPack) GetLeftNum() int32 {
	if x != nil {
		return x.LeftNum
	}
	return 0
}

func (x *GroupLogIDPack) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

type GroupLogNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GroupLogNum) Reset() {
	*x = GroupLogNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_admin_pull_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupLogNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLogNum) ProtoMessage() {}

func (x *GroupLogNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_admin_pull_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLogNum.ProtoReflect.Descriptor instead.
func (*GroupLogNum) Descriptor() ([]byte, []int) {
	return file_proto_group_admin_pull_proto_rawDescGZIP(), []int{2}
}

func (x *GroupLogNum) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_proto_group_admin_pull_proto protoreflect.FileDescriptor

var file_proto_group_admin_pull_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x22, 0x87, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4c, 0x6f, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0x40, 0x0a, 0x0e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67, 0x49, 0x44,
	0x50, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x6f, 0x67,
	0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_group_admin_pull_proto_rawDescOnce sync.Once
	file_proto_group_admin_pull_proto_rawDescData = file_proto_group_admin_pull_proto_rawDesc
)

func file_proto_group_admin_pull_proto_rawDescGZIP() []byte {
	file_proto_group_admin_pull_proto_rawDescOnce.Do(func() {
		file_proto_group_admin_pull_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_group_admin_pull_proto_rawDescData)
	})
	return file_proto_group_admin_pull_proto_rawDescData
}

var file_proto_group_admin_pull_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_group_admin_pull_proto_goTypes = []interface{}{
	(*GroupLogHash)(nil),   // 0: admin.pb.GroupLogHash
	(*GroupLogIDPack)(nil), // 1: admin.pb.GroupLogIDPack
	(*GroupLogNum)(nil),    // 2: admin.pb.GroupLogNum
}
var file_proto_group_admin_pull_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_group_admin_pull_proto_init() }
func file_proto_group_admin_pull_proto_init() {
	if File_proto_group_admin_pull_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_group_admin_pull_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupLogHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_admin_pull_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupLogIDPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_admin_pull_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupLogNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_group_admin_pull_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_group_admin_pull_proto_goTypes,
		DependencyIndexes: file_proto_group_admin_pull_proto_depIdxs,
		MessageInfos:      file_proto_group_admin_pull_proto_msgTypes,
	}.Build()
	File_proto_group_admin_pull_proto = out.File
	file_proto_group_admin_pull_proto_rawDesc = nil
	file_proto_group_admin_pull_proto_goTypes = nil
	file_proto_group_admin_pull_proto_depIdxs = nil
}
