// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/connect.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectMaintain_Type int32

const (
	ConnectMaintain_Heartbeat     ConnectMaintain_Type = 0
	ConnectMaintain_ConnectChange ConnectMaintain_Type = 1
)

// Enum value maps for ConnectMaintain_Type.
var (
	ConnectMaintain_Type_name = map[int32]string{
		0: "Heartbeat",
		1: "ConnectChange",
	}
	ConnectMaintain_Type_value = map[string]int32{
		"Heartbeat":     0,
		"ConnectChange": 1,
	}
)

func (x ConnectMaintain_Type) Enum() *ConnectMaintain_Type {
	p := new(ConnectMaintain_Type)
	*p = x
	return p
}

func (x ConnectMaintain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectMaintain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_connect_proto_enumTypes[0].Descriptor()
}

func (ConnectMaintain_Type) Type() protoreflect.EnumType {
	return &file_pb_connect_proto_enumTypes[0]
}

func (x ConnectMaintain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectMaintain_Type.Descriptor instead.
func (ConnectMaintain_Type) EnumDescriptor() ([]byte, []int) {
	return file_pb_connect_proto_rawDescGZIP(), []int{1, 0}
}

type ConnectInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BootTs    uint64 `protobuf:"varint,2,opt,name=boot_ts,json=bootTs,proto3" json:"boot_ts,omitempty"`
	ConnTimes uint64 `protobuf:"varint,3,opt,name=conn_times,json=connTimes,proto3" json:"conn_times,omitempty"`
}

func (x *ConnectInit) Reset() {
	*x = ConnectInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_connect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInit) ProtoMessage() {}

func (x *ConnectInit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_connect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInit.ProtoReflect.Descriptor instead.
func (*ConnectInit) Descriptor() ([]byte, []int) {
	return file_pb_connect_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectInit) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ConnectInit) GetBootTs() uint64 {
	if x != nil {
		return x.BootTs
	}
	return 0
}

func (x *ConnectInit) GetConnTimes() uint64 {
	if x != nil {
		return x.ConnTimes
	}
	return 0
}

type ConnectMaintain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ConnectMaintain_Type `protobuf:"varint,1,opt,name=type,proto3,enum=network.pb.ConnectMaintain_Type" json:"type,omitempty"`
	Payload   []byte               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ConnTimes uint64               `protobuf:"varint,3,opt,name=conn_times,json=connTimes,proto3" json:"conn_times,omitempty"`
}

func (x *ConnectMaintain) Reset() {
	*x = ConnectMaintain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_connect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectMaintain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMaintain) ProtoMessage() {}

func (x *ConnectMaintain) ProtoReflect() protoreflect.Message {
	mi := &file_pb_connect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMaintain.ProtoReflect.Descriptor instead.
func (*ConnectMaintain) Descriptor() ([]byte, []int) {
	return file_pb_connect_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectMaintain) GetType() ConnectMaintain_Type {
	if x != nil {
		return x.Type
	}
	return ConnectMaintain_Heartbeat
}

func (x *ConnectMaintain) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectMaintain) GetConnTimes() uint64 {
	if x != nil {
		return x.ConnTimes
	}
	return 0
}

var File_pb_connect_proto protoreflect.FileDescriptor

var file_pb_connect_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x62, 0x22, 0x60,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x74,
	0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x74, 0x54,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x22, 0xaa, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x61, 0x69, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_connect_proto_rawDescOnce sync.Once
	file_pb_connect_proto_rawDescData = file_pb_connect_proto_rawDesc
)

func file_pb_connect_proto_rawDescGZIP() []byte {
	file_pb_connect_proto_rawDescOnce.Do(func() {
		file_pb_connect_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_connect_proto_rawDescData)
	})
	return file_pb_connect_proto_rawDescData
}

var file_pb_connect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_connect_proto_goTypes = []interface{}{
	(ConnectMaintain_Type)(0), // 0: network.pb.ConnectMaintain.Type
	(*ConnectInit)(nil),       // 1: network.pb.ConnectInit
	(*ConnectMaintain)(nil),   // 2: network.pb.ConnectMaintain
}
var file_pb_connect_proto_depIdxs = []int32{
	0, // 0: network.pb.ConnectMaintain.type:type_name -> network.pb.ConnectMaintain.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_connect_proto_init() }
func file_pb_connect_proto_init() {
	if File_pb_connect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_connect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_connect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectMaintain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_connect_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_connect_proto_goTypes,
		DependencyIndexes: file_pb_connect_proto_depIdxs,
		EnumInfos:         file_pb_connect_proto_enumTypes,
		MessageInfos:      file_pb_connect_proto_msgTypes,
	}.Build()
	File_pb_connect_proto = out.File
	file_pb_connect_proto_rawDesc = nil
	file_pb_connect_proto_goTypes = nil
	file_pb_connect_proto_depIdxs = nil
}
