// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/routing_table.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RoutingTable) Reset() {
	*x = RoutingTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_routing_table_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTable) ProtoMessage() {}

func (x *RoutingTable) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routing_table_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTable.ProtoReflect.Descriptor instead.
func (*RoutingTable) Descriptor() ([]byte, []int) {
	return file_pb_routing_table_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingTable) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RoutingTable) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pb_routing_table_proto protoreflect.FileDescriptor

var file_pb_routing_table_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x70, 0x62, 0x22, 0x42, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_routing_table_proto_rawDescOnce sync.Once
	file_pb_routing_table_proto_rawDescData = file_pb_routing_table_proto_rawDesc
)

func file_pb_routing_table_proto_rawDescGZIP() []byte {
	file_pb_routing_table_proto_rawDescOnce.Do(func() {
		file_pb_routing_table_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_routing_table_proto_rawDescData)
	})
	return file_pb_routing_table_proto_rawDescData
}

var file_pb_routing_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_routing_table_proto_goTypes = []interface{}{
	(*RoutingTable)(nil), // 0: network.pb.RoutingTable
}
var file_pb_routing_table_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_routing_table_proto_init() }
func file_pb_routing_table_proto_init() {
	if File_pb_routing_table_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_routing_table_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_routing_table_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_routing_table_proto_goTypes,
		DependencyIndexes: file_pb_routing_table_proto_depIdxs,
		MessageInfos:      file_pb_routing_table_proto_msgTypes,
	}.Build()
	File_pb_routing_table_proto = out.File
	file_pb_routing_table_proto_rawDesc = nil
	file_pb_routing_table_proto_goTypes = nil
	file_pb_routing_table_proto_depIdxs = nil
}
