// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/group_log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志类型
type Log_Type int32

const (
	Log_CREATE  Log_Type = 0 // 创建群
	Log_NAME    Log_Type = 1 // 设置群名
	Log_NOTICE  Log_Type = 2 // 设置群公告
	Log_MEMBER  Log_Type = 3 // 群成员操作
	Log_DISBAND Log_Type = 4 // 解散群
)

// Enum value maps for Log_Type.
var (
	Log_Type_name = map[int32]string{
		0: "CREATE",
		1: "NAME",
		2: "NOTICE",
		3: "MEMBER",
		4: "DISBAND",
	}
	Log_Type_value = map[string]int32{
		"CREATE":  0,
		"NAME":    1,
		"NOTICE":  2,
		"MEMBER":  3,
		"DISBAND": 4,
	}
)

func (x Log_Type) Enum() *Log_Type {
	p := new(Log_Type)
	*p = x
	return p
}

func (x Log_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_group_log_proto_enumTypes[0].Descriptor()
}

func (Log_Type) Type() protoreflect.EnumType {
	return &file_pb_group_log_proto_enumTypes[0]
}

func (x Log_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Type.Descriptor instead.
func (Log_Type) EnumDescriptor() ([]byte, []int) {
	return file_pb_group_log_proto_rawDescGZIP(), []int{0, 0}
}

// 群成员具体操作
type Log_Operate int32

const (
	Log_INVITE   Log_Operate = 0 // 邀请
	Log_AGREE    Log_Operate = 1 // 同意
	Log_REJECTED Log_Operate = 2 // 拒绝
	Log_APPLY    Log_Operate = 3 // 申请
	Log_REMOVE   Log_Operate = 4 // 移除
)

// Enum value maps for Log_Operate.
var (
	Log_Operate_name = map[int32]string{
		0: "INVITE",
		1: "AGREE",
		2: "REJECTED",
		3: "APPLY",
		4: "REMOVE",
	}
	Log_Operate_value = map[string]int32{
		"INVITE":   0,
		"AGREE":    1,
		"REJECTED": 2,
		"APPLY":    3,
		"REMOVE":   4,
	}
)

func (x Log_Operate) Enum() *Log_Operate {
	p := new(Log_Operate)
	*p = x
	return p
}

func (x Log_Operate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Operate) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_group_log_proto_enumTypes[1].Descriptor()
}

func (Log_Operate) Type() protoreflect.EnumType {
	return &file_pb_group_log_proto_enumTypes[1]
}

func (x Log_Operate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Operate.Descriptor instead.
func (Log_Operate) EnumDescriptor() ([]byte, []int) {
	return file_pb_group_log_proto_rawDescGZIP(), []int{0, 1}
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 日志ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 群组ID
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 操作人
	PeerId string `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// 日志类型
	Type Log_Type `protobuf:"varint,4,opt,name=type,proto3,enum=admin.pb.Log_Type" json:"type,omitempty"`
	// 成员ID
	MemberId string `protobuf:"bytes,5,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// 成员操作
	Operate Log_Operate `protobuf:"varint,6,opt,name=operate,proto3,enum=admin.pb.Log_Operate" json:"operate,omitempty"`
	// 附带内容
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// 时间戳
	Timestamp int32 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// lamport时间戳
	Lamportime uint64 `protobuf:"varint,9,opt,name=lamportime,proto3" json:"lamportime,omitempty"`
	// 签名
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_group_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_pb_group_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_pb_group_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Log) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Log) GetType() Log_Type {
	if x != nil {
		return x.Type
	}
	return Log_CREATE
}

func (x *Log) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Log) GetOperate() Log_Operate {
	if x != nil {
		return x.Operate
	}
	return Log_INVITE
}

func (x *Log) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Log) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetLamportime() uint64 {
	if x != nil {
		return x.Lamportime
	}
	return 0
}

func (x *Log) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pb_group_log_proto protoreflect.FileDescriptor

var file_pb_group_log_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x22, 0xbf,
	0x03, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2f, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x61,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x41, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41,
	0x4d, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x49, 0x53, 0x42, 0x41, 0x4e, 0x44, 0x10, 0x04, 0x22, 0x45, 0x0a, 0x07, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x47, 0x52, 0x45, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x50, 0x50,
	0x4c, 0x59, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x04,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_group_log_proto_rawDescOnce sync.Once
	file_pb_group_log_proto_rawDescData = file_pb_group_log_proto_rawDesc
)

func file_pb_group_log_proto_rawDescGZIP() []byte {
	file_pb_group_log_proto_rawDescOnce.Do(func() {
		file_pb_group_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_group_log_proto_rawDescData)
	})
	return file_pb_group_log_proto_rawDescData
}

var file_pb_group_log_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_group_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_group_log_proto_goTypes = []interface{}{
	(Log_Type)(0),    // 0: admin.pb.Log.Type
	(Log_Operate)(0), // 1: admin.pb.Log.Operate
	(*Log)(nil),      // 2: admin.pb.Log
}
var file_pb_group_log_proto_depIdxs = []int32{
	0, // 0: admin.pb.Log.type:type_name -> admin.pb.Log.Type
	1, // 1: admin.pb.Log.operate:type_name -> admin.pb.Log.Operate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_group_log_proto_init() }
func file_pb_group_log_proto_init() {
	if File_pb_group_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_group_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_group_log_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_group_log_proto_goTypes,
		DependencyIndexes: file_pb_group_log_proto_depIdxs,
		EnumInfos:         file_pb_group_log_proto_enumTypes,
		MessageInfos:      file_pb_group_log_proto_msgTypes,
	}.Build()
	File_pb_group_log_proto = out.File
	file_pb_group_log_proto_rawDesc = nil
	file_pb_group_log_proto_goTypes = nil
	file_pb_group_log_proto_depIdxs = nil
}
