// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/alive.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId    string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Lamportime uint64 `protobuf:"varint,2,opt,name=lamportime,proto3" json:"lamportime,omitempty"`
}

func (x *GroupAlive) Reset() {
	*x = GroupAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_alive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAlive) ProtoMessage() {}

func (x *GroupAlive) ProtoReflect() protoreflect.Message {
	mi := &file_pb_alive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAlive.ProtoReflect.Descriptor instead.
func (*GroupAlive) Descriptor() ([]byte, []int) {
	return file_pb_alive_proto_rawDescGZIP(), []int{0}
}

func (x *GroupAlive) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupAlive) GetLamportime() uint64 {
	if x != nil {
		return x.Lamportime
	}
	return 0
}

var File_pb_alive_proto protoreflect.FileDescriptor

var file_pb_alive_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x62, 0x22, 0x47, 0x0a, 0x0a,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x61, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_alive_proto_rawDescOnce sync.Once
	file_pb_alive_proto_rawDescData = file_pb_alive_proto_rawDesc
)

func file_pb_alive_proto_rawDescGZIP() []byte {
	file_pb_alive_proto_rawDescOnce.Do(func() {
		file_pb_alive_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_alive_proto_rawDescData)
	})
	return file_pb_alive_proto_rawDescData
}

var file_pb_alive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_alive_proto_goTypes = []interface{}{
	(*GroupAlive)(nil), // 0: network.pb.GroupAlive
}
var file_pb_alive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_alive_proto_init() }
func file_pb_alive_proto_init() {
	if File_pb_alive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_alive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_alive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_alive_proto_goTypes,
		DependencyIndexes: file_pb_alive_proto_depIdxs,
		MessageInfos:      file_pb_alive_proto_msgTypes,
	}.Build()
	File_pb_alive_proto = out.File
	file_pb_alive_proto_rawDesc = nil
	file_pb_alive_proto_goTypes = nil
	file_pb_alive_proto_depIdxs = nil
}
